apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-label
  labels:
    environment: local
    version: 1.0.0
spec:
  containers:
    - name: nginx-with-label
      image: nginx
      ports:
        - containerPort: 80