apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs-match-expression
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx-rs
      - key: env
        operator: In
        values:
          - local
          - dev
          - prod
  template:
    metadata:
      name: nginx-rs
      labels:
        app: nginx-rs
        env: local
    spec:
      containers:
        - name: cont-nginx-rs
          image: nginx