apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: rs-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-service-app
  template:
    metadata:
      name: nginx
      labels:
        name: nginx-service-app
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  selector:
    name: nginx-service-app
  ports:
    - port: 8080
      targetPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: curl-nginx
spec:
  containers:
    - name: curl-nginx
      image: khannedy/nginx-curl